# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.1
_src_path: gh:algorandfoundation/algokit-python-template
author_email: anchitgoel5@gmail.com
author_name: anchit-goel
contract_name: pharma_clear
deployment_language: python
preset_name: production
project_name: PharmaClear-contracts

