# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.8
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: anchitgoel5@gmail.com
author_name: anchit-goel
cloud_provider: none
contract_name: pharma_clear
deployment_language: python
preset_name: production
project_name: PharmaClear

